export const DEFAULT_REPORT_LINES = [
  '',
  `┌─ measurements ${'─'.repeat(48)}`,
  '│ first run      1.80s   budget 462ms   3.9× over',
  '│ on its own     889ms   still over budget',
  '│ tests             38   47ms each   20× the median test',
  `├─ slowest tests ${'─'.repeat(47)}`,
  '│   79ms  focusables > have focusable elements',
  '│   29ms  opened controls > sends UI event',
  `├─ where the time went · CPU profile, 738ms sampled ${'─'.repeat(12)}`,
  `│ hooks        ${'█'.repeat(11)}${'░'.repeat(9)} 54%   test bodies 46%`,
  `│ by package   ${'█'.repeat(6)}${'░'.repeat(14)}  29%  jsdom`,
  `│              ${'█'.repeat(5)}${'░'.repeat(15)}  24%  @angular/core`,
  `│              ${'█'.repeat(2)}${'░'.repeat(18)}   9%  zone.js`,
  '│ in the spec  setUpWith 39%  ·  assertFocus 8%',
  '│ your code    removeAllRootElements 2%',
  '│ hottest      (garbage collector) 3%',
  `├─ likely cause ${'─'.repeat(48)}`,
  '│ Most of the time is set-up that every test repeats: 54% is in hooks — setUpWith alone is 39%. Build what does not change once, in a beforeAll, or render less per test.',
  '│ The largest single cost is jsdom (29%): rendering and change detection, which grow with the size of the tree each test builds.',
  `└${'─'.repeat(63)}`,
  '',
];
