export const OPTION_SETS_NOT_RECOGNISED = [
  "{ onlyMethodsToSpyOn: ['seek', 'play'], passthrough: true }",
  "{ onlyMethodsToSpyOn: ['seek'] }",
  "{ methodsToSpyOn: ['seek'], passthrough: true }",
  "{ onlyMethodsToSpyOn: ['seek'], passthrough: false }",
  "{ onlyMethodsToSpyOn: ['seek'], passthrough: flag }",
  "{ onlyMethodsToSpyOn: ['seek'], passthrough: true, strict: true }",
  '{ onlyMethodsToSpyOn: methods, passthrough: true }',
  '{ onlyMethodsToSpyOn: [name], passthrough: true }',
  "{ onlyMethodsToSpyOn: ['a-b'], passthrough: true }",
  '{ onlyMethodsToSpyOn: [,], passthrough: true }',
  "{ ...base, onlyMethodsToSpyOn: ['seek'] }",
  "{ onlyMethodsToSpyOn: ['close'], returns: { play: undefined } }",
  "{ onlyMethodsToSpyOn: ['close'], returns: { close: null } }",
  "{ onlyMethodsToSpyOn: ['close'], returns: { close: nothing } }",
  "{ onlyMethodsToSpyOn: ['close'], returns: { close: undefined, play: undefined } }",
  "{ onlyMethodsToSpyOn: ['close'], returns: { ...seeds } }",
  "{ onlyMethodsToSpyOn: ['close'], returns: seeds }",
  "{ returns: { 'a-b': undefined } }",
  '{ passthrough: true }',
  'options',
];

export function multiMemberUsages(own: string): string[] {
  return [
    `const spy = createSpyFromInstance(player, ${own});\nspy.seek();\nspy.play();`,
    `const spy = createSpyFromInstance(player, ${own});\nspy.seek = vi.fn();`,
    `const spy = createSpyFromInstance(player, ${own});\nhandOver(spy);`,
    `const spy = createSpyFromInstance(player, ${own});\nspy[key]();`,
    `let spy = createSpyFromInstance(player, ${own});\nspy = other;`,
    `export const spy = createSpyFromInstance(player, ${own});`,
    `using spy = createSpyFromInstance(player, ${own});`,
    `const { seek, play } = createSpyFromInstance(player, ${own});`,
    `const {} = createSpyFromInstance(player, ${own});`,
    `const { play } = createSpyFromInstance(player, ${own});`,
    `const { seek: { calls } } = createSpyFromInstance(player, ${own});`,
    `const { seek = fallback } = createSpyFromInstance(player, ${own});`,
    `const { ...rest } = createSpyFromInstance(player, ${own});`,
    `const [first] = createSpyFromInstance(player, ${own});`,
    `createSpyFromInstance(player, ${own}).play;`,
    `createSpyFromInstance(player, ${own}).seek = vi.fn();`,
    `return createSpyFromInstance(player, ${own});`,
    `this.spy = createSpyFromInstance(player, ${own});`,
    `const held = (spy = createSpyFromInstance(player, ${own}));`,
    `spy = createSpyFromInstance(player, ${own});`,
    `function setUp(spy) {\n  spy = createSpyFromInstance(player, ${own});\n}`,
    `let { spy } = {};\nspy = createSpyFromInstance(player, ${own});`,
  ];
}
